spring:
  application:
    name: name=enrolment-system

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb  # URL de conexão para um banco de dados em memória
    username: sa              # Usuário padrão do H2
    password:                 # Senha vazia por padrão

    h2:
      console:
        enabled: true           # Habilita a console web do H2
        path: /h2-console   
