networks:
  alura_network:
    driver: bridge

services:
  enrolment-system:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: enrolment-system
    working_dir: /home/enrolment-system
    env_file:
      - ./enrolment-system.env
    ports:
      - 8080:8080
    volumes:
      - ../:/home/enrolment-system/:rw
    command: mvn spring-boot:run
    networks:
      - alura_network

  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - ./mysql.env
    ports:
      - 3306:3306
    networks:
      - alura_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - alura_network