networks:
  alura-network:
    driver: bridge

services:
  enrolment-system:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: enrolment-system
    restart: always
    working_dir: /home/enrolment-system
    env_file:
      - ./enrolment-system.env
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"            
          }'
    ports:
      - 8080:8080
    volumes:
      - ../:/home/enrolment-system/:rw
    command: mvn spring-boot:run -DskipTests
    depends_on:
      - mysql
    networks:
      - alura-network

  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - ./enrolment-system.env
    ports:
      - 3307:3306
    networks:
      - alura-network
